### ISSUE TITLE
Inputs are very laggy with complicated rig.jsons

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-metadata-entry-js#162] opened 2024-04-02 21:05 UTC
**Describe the bug**
A few users have reported noticeable lagging when entering complex rig metadata. For example, dropdowns take a few seconds to render, or the text input would not change the displayed value as the user is typing.

**To Reproduce**
1. Go to https://metadata-entry.allenneuraldynamics.org/
2. Click on 'Select schema' dropdown and select Rig
3. Scroll down to add multiple subschemas.
4. Observe that the input fields have more delay as the formData gets longer.

**Expected behavior**
We should investigate this and see if it is an issue with rjsf, our custom widgets, or the Rig JSON schema itself.

**Desktop (please complete the following information):**
- Browser: Chrome, Edge

**Additional context**
I did a quick comparison and noticed comparable lagging even without the `CustomTextWidget` and also on [rjsf playground](https://rjsf-team.github.io/react-jsonschema-form/).

**Comment by dyf** [comment] 2024-04-03 00:36
dupe of #159

**Comment by helen-m-lin** [comment] 2024-04-22 20:54
Profiling shows that for empty Rig, we have keyboard events taking approx. 200ms to process, and for "filled" Rig each keyboard event can take up to 2.5s. The performance issue is due to a few embedded calls to 
`AJV8Validator.isValid()` and `Ajv.addSchema()`- 94% of total time is spent through json-schema-traverse

Relevant issue in RJSF repo: https://github.com/rjsf-team/react-jsonschema-form/issues/3715

I will do some more profiling and look at ways to mitigate or improve the performance.

![Image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/46795546/34df3035-8a54-46c7-86ca-73d91296e79b)

![Image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/46795546/c5ba851d-23ad-4d26-9d22-b3de0be0a142)

**Comment by helen-m-lin** [comment] 2024-04-23 19:33
Bulk of performance issues are linked to `liveOmit` in the RJSF form because `liveOmit` runs AJV validator on every change/keystroke.
- We have `liveOmit` and `omitExtraData` enabled so that extra data gets removed (required for discriminators)
- Without `liveOmit`: performance improves from 250-350ms per keystroke on an empty Rig to 70-100ms (negligible). For a "filled" sample Rig, improves from 2-2.6s to 350-500ms (acceptable).

**Mitigation: Disable `liveOmit` option in RJSF form**
- This is a 1-line change on our part. We still need `omitExtraData`, just not on each keystroke. When users click submit, RJSF should still first omit extra data, then pass new formData to validator.

**Blocker: Potential bug in RJSF with `omitExtraData`**
- If we remove `liveOmit`, we now have errors due to extra data that users cannot manually resolve.
- Looking into RJSF code, I have some ideas why it is failing. I'll file a bug with RJSF to check with them, and also look into any temporary work-arounds.

**Closed** 2024-05-02 22:24 UTC
